### PR TITLE
Minor 2.0 fixes

### PR DESCRIPTION
**Pull request by trym-b**

### CODE REVIEW

**Comment by eskaur** [comment]
By the way, I just merged my Calibration fixes to the release-candidate-2.0 branch. Can you rebase? :)

**Review by anordal — APPROVED** [review]

**Comment by eskaur** [comment]
Since we have no unit-tests for toSnakeCase: Has this been properly tested?

**Comment by trym-b** [comment]
I haven't really tested this, I got some patch files from @anordal. Assuming that all tests passes, then I would think all of the functions/modules has the correct names.

**Comment by eskaur** [comment]
Ah it is in fact used during build. For some reason I thought it was (almost) dead code since we haven't deployed the code-generation yet.

Never mind then. :)

**Comment by anordal** [comment]
The patch is #91. Just an equivalence transform from my side. I haven't tested it by itself either.

**Review by eskaur — APPROVED** [review]

**Pull request merged**
