### PR TITLE
#65 update copyright year

### PR DESCRIPTION
**Pull request by torbsorb**
Issue #65

### CODE REVIEW

**Comment by knatten** [comment]
Bump @torbsorb

**Comment by torbsorb** [comment]
> 
> 
> Bump @torbsorb

Updated now

**Comment by knatten** [comment]
Attn. @nedrebo

**Comment by nedrebo** [comment]
I never seen with braces before. Else :+1:

This is what we have in Zivid SDK (except we have an regression right now)

```
/*******************************************************************************
 * This file is part of the Zivid 3D Camera API
 *
 * Copyright 2015-2019 (C) Zivid AS
 * All rights reserved.
 * 
 * Zivid Software License, v1.0
```

**Comment by torbsorb** [comment]
FYI @nedrebo, updated

**Comment by nedrebo** [comment]
Thx

**Pull request merged**
