### PR TITLE
Test

### PR DESCRIPTION
**Pull request by eskaur**
This is just a test-PR. Do not merge.

### CODE REVIEW

**Comment by eskaur** [comment]
@trym-b : Got duplicate workflows when pushing an update to this branch, which contradicts the premise for merging https://github.com/zivid/zivid-python/pull/119.

**Comment by trym-b** [comment]
That is unfortunate. And also surprising. Not sure how we are going to let forks build the CI for `zivid-python`.

**Comment by eskaur** [comment]
What about instead allowing manual triggering with "workflow_dispatch" that we can do in the rare case of an external PR?

**Comment by trym-b** [comment]
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-using-a-list-of-events

Perhaps there are some subtle differences when we use a different syntax?

**Comment by eskaur** [comment]
Does it say anywhere in the docs that we should not expect duplicate workflows when multiple conditions are met?

**Comment by trym-b** [comment]
The other syntax did not work: https://github.com/zivid/zivid-python/pull/130

There must be a correct way to do this.

**Comment by trym-b** [comment]
I give up, I will create a PR that revert the previous commit

**Comment by trym-b** [comment]
https://github.com/zivid/zivid-python/pull/131

**Pull request closed without merging**
